#include "BufferStructure.h"

/* TODO THIS WILL BE IMPLEMENTED WHEN VERTEX BUFFER DATA BECOMES INTERLOCKED INTO A SINGLE BUFFER
 * I.E. WHEN USING BATCH RENDERING. THE CLASS WILL ALLOW FOR DEFINING THE STRUCTURE/LAYOUT OF A BUFFER,
 * INCLUDING STRIDE, OFFSET AND SIZE OF EACH SUB-DATA-SEGMENT AND WHICH SHADER LAYOUT ID THEY RELATE TO*/
